### ISSUE TITLE
BUG: SECURITY PROBLEM / Login possible without login

### ISSUE THREAD

**Issue by DESK-coder** [dbgate/dbgate#1029]
**Describe the bug**
If you use the following docker-compose and want to work with the enviroment flag “LOGIN”, “PASSWORD” etc., you can still log in completely without username and password and get a JWT-Auth, which allows access to all connections.

**To Reproduce**
```yaml
services:
  dbgate:
    image: dbgate/dbgate
    restart: always
    ports:
      - 8080:3000
    volumes:
      - dbgate-data:/root/.dbgate
    environment:

      - LOGIN=dummy
      - LOGIN_PASSWORD_dummy=dummy
      - LOGIN_PERMISSIONS_dummy=~connections/*,connections/dev_customers

      - CONNECTIONS=dev_customers,stage_customers,prod_customers

      - LABEL_dev_customers=[DEV] customers
      - SERVER_dev_customers=database.dev
      - PORT_dev_customers=5432
      - ENGINE_dev_customers=postgres@dbgate-plugin-postgres
      - USER_dev_customers=devlogin
      - DATABASE_dev_customers=devpass

      - LABEL_stage_customers=[STAGE] customers
      - SERVER_stage_customers=database.stage
      - PORT_stage_customers=5432
      - ENGINE_stage_customers=postgres@dbgate-plugin-postgres
      - USER_stage_customers=stagelogin
      - DATABASE_stage_customers=stagepass

      - LABEL_prod_customers=[PROD] customers
      - SERVER_prod_customers=database.production
      - PORT_prod_customers=5432
      - ENGINE_prod_customers=postgres@dbgate-plugin-postgres
      - USER_prod_customers=prodlogin
      - DATABASE_prod_customers=securepass

volumes:
  dbgate-data:
    driver: local
```

**Expected behavior**
An error message that the login is invalid, or a login, but no view of the tables.

**Version Information (please complete the following information):**
 - OS: Ubuntu 24.04 LTS
 - App Version: 6.1.4
 - Install source: Docker compose
 - Type: Web
