### ISSUE TITLE
QUESTION: Trouble configuring OAuth with environment variables

### ISSUE THREAD

**Issue by alanrichman** [dbgate/dbgate#1071]
We are using the `dbgate/dbgate:6.2.1-alpine` container image for our DbGate deployment on the Community edition. I have configured OAuth environment variables like such:

```yaml
env:
  - name: OAUTH_OAUTH
    value: https://keycloak.mydomain.com/realms/myrealm/protocol/openid-connect/auth
  - name: OAUTH_TOKEN
    value: https://keycloak.mydomain.com/realms/myrealm/protocol/openid-connect/token
  - name: OAUTH_LOGOUT
    value: https://keycloak.mydomain.com/realms/myrealm/protocol/openid-connect/logout
  - name: OAUTH_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: dbgate-oidc
        key: CLIENT_ID
  - name: OAUTH_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: dbgate-oidc
        key: CLIENT_SECRET
  - name: OAUTH_LOGIN_FIELD
    value: email
  - name: OAUTH_SCOPE
    value: "openid email"
```

I am following the docs here: https://dbgate.org/docs/env-variables/

When I go to the URL I have setup for this deployment it will flash a login screen but then progress to the app without any user interaction. I have tried from fresh browser profiles and even another device to make sure that there are no tokens hiding anywhere.
