### ISSUE TITLE
BUG: Clickhouse VIEW are not available in UI if the user doesn't have an access to information_schema table

### ISSUE THREAD

**Issue by mbrekhov** [dbgate/dbgate#1076]
Hi!

When a user has **SELECT** access to the View, but doesn't have an  access to **information_schema** table, the view is not showing up in the dbgate UI.

It seems the root cause of the problem is this code - https://github.com/dbgate/dbgate/blob/v6.3.0/plugins/dbgate-plugin-clickhouse/src/backend/sql/views.js

I am attaching the  docker compose file and init.sql file to reproduce the problem

**compose.yaml**

```
  main_dbgate:
    image: "dbgate/dbgate:6.3.0-alpine"
    container_name: "test_dbgate"
    restart: "always"
    ports:
      - "21337:3000"
    depends_on:
      ch:
        condition: service_healthy
    environment:
      WEB_ROOT: "/"
      SHELL_CONNECTION: 0
      SHELL_SCRIPTING: 0
      LOG_LEVEL: trace

      LOGINS: "admin"
      LOGIN_PASSWORD_admin: "password"
      LOGIN_PERMISSIONS_admin: "~widgets/*,widgets/database,widgets/file,widgets/history"

      CONNECTIONS: "ch"
      LABEL_ch: "ch"
      URL_ch: "http://ro_user:password@ch:8123?request_timeout=90000"
        #URL_ch: "http://default:password@ch:8123?request_timeout=90000"
      ENGINE_ch: "clickhouse@dbgate-plugin-clickhouse"
    networks: ["mynetwork"]


  ch:
    image: clickhouse/clickhouse-server:24.10
    container_name: clickhouse-server
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      CLICKHOUSE_DB: 'dbgate_test_db'
      CLICKHOUSE_USER: 'default'
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: '1'
      CLICKHOUSE_PASSWORD: 'password'
    deploy:
      resources:
        limits:
          cpus: "0.2"
    ulimits:
      nofile: 262144 
    networks: ["mynetwork"]

    healthcheck:
      test: wget --no-verbose --tries=1 http://127.0.0.1:8123/ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 6

networks:
  mynetwork:
```

**init.sql**
```
CREATE VIEW dbgate_test_db.test_view as select now();

CREATE ROLE ro_role;
GRANT SELECT ON dbgate_test_db.* to ro_role;

CREATE USER ro_user  IDENTIFIED WITH sha256_password BY 'password';
GRANT ro_role TO ro_user;
SET DEFAULT ROLE ro_role TO ro_user;
```

Run it as **docker compose up -d**
Then login to http://127.0.0.1:21337/ under **admin/password** credentials

When the URL_ch connection in the compose file is set to use **ro_user** - you will not see **dbgate_test_db.test_view**  in UI (but will be able to select from it, because you have SELECT permission to the dbgate_test_db.*) 
If you change URL_ch connection to use **default** user - the dbgate_test_db.test_view will show up in the UI

![Image](https://github.com/user-attachments/assets/2130e617-1e0b-4751-86b7-ce93eb013583)
![Image](https://github.com/user-attachments/assets/9f419502-565e-44ba-a8ea-9bbaebf334a7)
