### ISSUE TITLE
FEAT: Allow sqlite connection flags

### ISSUE THREAD

**Issue by meglio** [dbgate/dbgate#1078]
In my case, I specify database connection in docker compose environment variables, like this:

```
environment:
    CONNECTIONS: perf
    LABEL_perf: Perf SQLite
    ENGINE_perf: sqlite@dbgate-plugin-sqlite
    FILE_perf: /app/sqlite/data/perf.sqlite
```

Looks like if no database exists, it still automatically creates it. I'd like to switch that off. It would presumably be an easy fix if I could specify connection flags, among which there is a flag to create database automatically if it does not exists. This flag is on by default. It would be nice if I'd actually configure those flags via environment variables and thus be able to prevent automatic sqlite creation.

**Comment by janproch** [comment]
I am not sure, what sould be behaviour of application, if database file doesn't exist.

Maybe if you describe you use case a little bit more, I could better figure what you want.

In other words - why are you creating connection to non existing file, if you don't want to create it?

Thanks

**Comment by meglio** [comment]
> what sould be behaviour of application, if database file doesn't exist.

Well I suggested the solution:

> It would presumably be an easy fix if I could specify connection flags, among which there is **a flag to create database automatically if it does not exists**. 

-----

> why are you creating connection to non existing file, if you don't want to create it?

Starting a container does not mean creating a connection. As one of many examples, when this container is part of Docker Compose, it starts togher with all other containers. Until I actually open the UI and try to connect to the database / explore it, I'm not connecting. 

-----

> If you describe you use case a little bit more

My use case is, I would prefer for dbgate to not create any sqlite database until I actually try to connect (starting a container does not count), and only if it is configured to do so. It's a simple boolean configuration that adds flexibility. It might well be that discussing it is longer than implementing it :)

**Comment by janproch** [comment]
So you would like to make configuration like this:

```yaml
environment:
    CONNECTIONS: perf
    LABEL_perf: Perf SQLite
    ENGINE_perf: sqlite@dbgate-plugin-sqlite
    FILE_perf: /app/sqlite/data/perf.sqlite
    TESTIFEXISTS_perf: true
```

And if file /app/sqlite/data/perf.sqlite will not exists, connection to database perf will fail?
