### ISSUE TITLE
BUG: ClickHouse plugin defaults to localhost instead of configured server/port in Docker environment

### ISSUE THREAD

**Issue by DXAizpiri** [dbgate/dbgate#1106]
## Summary
The ClickHouse plugin in DbGate ignores the configured SERVER/PORT environment variables after initial connection, defaulting to 127.0.0.1:8123 for subsequent operations when running in Docker environment.

## Description
When using DbGate via the official Docker image (`dbgate/dbgate:latest`) with a pre-configured ClickHouse connection (using environment variables in docker-compose.yml), the connection initially appears correctly in the connections list. However, attempting any operation after the initial connection consistently fails with:

```
connect ECONNREFUSED 127.0.0.1:8123
```

This error occurs even though the connection is properly configured with `SERVER_chlocal=clickhouse-local` (Docker service name) and appropriate port settings. The plugin correctly uses the configuration for the initial listing/ping but then defaults to 127.0.0.1:8123 for all subsequent operations.

## Steps to reproduce

1. Use the provided docker-compose.yml and associated init scripts
2. Ensure a clean Docker environment (`docker-compose down -v` and optionally `docker system prune -a --volumes`)
3. Run `docker-compose up -d` and wait for all services to become healthy
4. Open a web browser (preferably incognito mode) and navigate to http://localhost:8080
5. In the "CONNECTIONS" panel, click on the pre-configured "Local ClickHouse Docker" connection
6. Click on the `test_db` database listed under the connection
7. Observe the message "Database test_db is empty or structure is not loaded" and click the "Refresh" button
8. An error popup appears with `connect ECONNREFUSED 127.0.0.1:8123`

**Alternative reproduction path:**
- Try creating a new table via the UI within the test_db database
- When saving, the same `connect ECONNREFUSED 127.0.0.1:8123` error occurs

## Expected behavior
DbGate should consistently use the `SERVER_chlocal` (clickhouse-local) and `PORT_chlocal` values provided in the environment variables for all communications with the ClickHouse server, including schema refresh, data querying, and DDL execution. Operations should succeed without connection errors related to 127.0.0.1. The table `sample_table` created by the init script should be visible after refreshing.

## Version information

- **OS**: Windows 11 Pro 23H2 (Running Docker Desktop v4.41.1)
- **App Version**: Latest Docker tag as of 2025-05-05
- **Install source**: Docker (`dbgate/dbgate:latest` image)
- **Type**: Web (accessed via browser)
- **Database engine**: ClickHouse (`clickhouse/clickhouse-server:latest` image)

## Troubleshooting Already Performed

1. Confirmed the clickhouse-local container is running and healthy via `docker ps` and its own healthcheck (`wget ... /ping`).
2. Confirmed that the ClickHouse initialization scripts (init.sh and schema.data) **execute successfully**, creating the test_db database and sample_table with data. This was verified by:
   * Reviewing `docker logs clickhouse-local` which shows the execution of init scripts.
   * Manually connecting to the clickhouse-local container via `docker exec -it clickhouse-local clickhouse-client -u default --password <your_password>` and successfully running `SHOW DATABASES;`, `USE test_db;`, `SHOW TABLES;`, and `SELECT * FROM sample_table;` (which returns the expected rows).
3. Confirmed network connectivity between the dbgate-web container and the clickhouse-local container on port 8123 using `wget -O - http://clickhouse-local:8123/ping` from within the dbgate-web container (returns `Ok.`).
4. Confirmed via `docker inspect dbgate-web` that all configured environment variables (including SERVER_chlocal, PORT_chlocal, USER_chlocal, PASSWORD_chlocal, DATABASE_chlocal, ENGINE_chlocal) are correctly passed to the container.
5. Tested configuring PORT_chlocal to both 8123 (HTTP) and 9000 (Native TCP) - the error persists, always referencing 127.0.0.1:8123.
6. Tested removing the DATABASE_chlocal variable - the connection still fails with the same error when attempting operations.
7. Tested using the URL_chlocal variable - this resulted in a different error ("ClickHouse URL protocol must be either http or https").
8. Verified the ENGINE_chlocal value (clickhouse@dbgate-plugin-clickhouse) matches the plugin directory structure in the source code.

## Additional Context
This persistent attempt to connect to 127.0.0.1:8123 despite configuration strongly suggests a bug within the `dbgate-plugin-clickhouse` where the configured host/port is not being used for all required operations.

It's worth noting that the same project setup also includes a Cassandra database connection configured in an identical manner (using `SERVER_casslocal`, `PORT_casslocal`, etc. environment variables), and the Cassandra plugin works perfectly without any connection issues. All operations including schema refreshing, data viewing, and table creation function as expected with the Cassandra connection. This further suggests the issue is specific to the ClickHouse plugin implementation rather than a general problem with DbGate's Docker environment variable handling.

## Relevant files & Screenshots
**docker-compose.yml**
```
name: multi-db-dbgate

services:
  # --- Cassandra Service ---
  cassandra:
    image: cassandra:latest
    container_name: cassandra-dbgate
    ports:
      - "9042:9042"
    volumes:
       - cassandra_data:/var/lib/cassandra # Persist Cassandra data
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_RPC_ADDRESS=0.0.0.0 # Allow all connections for local dev
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 40s

  # --- Cassandra Initializer ---
  cassandra-init:
    image: cassandra:latest
    container_name: cassandra-init-script
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./init-scripts/cassandra/init.cql:/init.cql
    command: >
      sh -c "echo 'Waiting for Cassandra...' && sleep 10 &&
             echo 'Running Cassandra init.cql script...' &&
             cqlsh cassandra-dbgate -f /init.cql &&
             echo 'Cassandra script init.cql executed.'"
    restart: on-failure

  # --- ClickHouse Service ---
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-local
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native TCP interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse/ # Persist ClickHouse data
      - ./init-scripts/clickhouse:/docker-entrypoint-initdb.d
    environment:
      - CLICKHOUSE_PASSWORD=mysecretpassword
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--timeout=2", "-O", "/dev/null", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  # --- dbgate Service ---
  dbgate:
    image: dbgate/dbgate:latest
    container_name: dbgate-web
    restart: always
    ports:
      - "8080:3000" # Map host port 8080 to container port 3000
    volumes:
      - dbgate-data:/root/.dbgate # Persist dbgate data
    environment:
      - CONNECTIONS=casslocal,chlocal
      # Properties for 'casslocal' (Cassandra)
      - LABEL_casslocal=Local Cassandra Docker
      - SERVER_casslocal=cassandra-dbgate
      - PORT_casslocal=9042
      - DATABASE_casslocal=my_keyspace
      - ENGINE_casslocal=cassandra@dbgate-plugin-cassandra
      # Properties for 'chlocal' (ClickHouse)
      - LABEL_chlocal=Local ClickHouse Docker
      - SERVER_chlocal=clickhouse-local
      - PORT_chlocal=9000
      - USER_chlocal=default
      - PASSWORD_chlocal=mysecretpassword
      - DATABASE_chlocal=test_db          # Specifying default database
      - ENGINE_chlocal=clickhouse@dbgate-plugin-clickhouse
    depends_on:
      cassandra:
        condition: service_healthy
      clickhouse:
        condition: service_healthy

# --- Volumes Definition ---
volumes:
  dbgate-data:
    driver: local
  cassandra_data:
    driver: local
  clickhouse_data:
    driver: local
```
**init-scripts/clickhouse/init.sh**
```
#!/bin/bash
set -e # Exit immediately if a command exits with a non-zero status.

echo "ClickHouse Init Script: Waiting 5 seconds for server readiness..."
sleep 5

echo "ClickHouse Init Script: Running schema.data content..."
# The entrypoint script usually configures the client to use
# CLICKHOUSE_USER/CLICKHOUSE_PASSWORD automatically.
# We redirect the SQL file content to the client.
clickhouse-client -n < /docker-entrypoint-initdb.d/01_schema

echo "ClickHouse Init Script: Finished."
```
**init-scripts\clickhouse\01_schema**
```
-- Create database if it doesn't exist
CREATE DATABASE IF NOT EXISTS test_db;

-- Create a sample table in the new database
CREATE TABLE IF NOT EXISTS test_db.sample_table (
    id UInt64,
    message String,
    timestamp DateTime DEFAULT now()
) ENGINE = MergeTree()
ORDER BY id;

-- Insert some dummy data
INSERT INTO test_db.sample_table (id, message) VALUES (1, 'Hello ClickHouse!');
INSERT INTO test_db.sample_table (id, message) VALUES (2, 'dbgate is connecting...');
INSERT INTO test_db.sample_table (id, message) VALUES (3, 'Data initialized.');
```

![Image](https://github.com/user-attachments/assets/328f86af-f73b-41bc-9f0c-5c3af607e343)

![Image](https://github.com/user-attachments/assets/4bde2085-4501-4120-b09e-a12df88821ae)
