### ISSUE TITLE
FEAT: Load theme when loading app

### ISSUE THREAD

**Issue by LunarTwilight** [dbgate/dbgate#316]
**Is your feature request related to a problem? Please describe.**
I host dbgate on my server, when I open the URL in chrome, I get a flash of white via the loading screen before dbgate opens fully and the dark theme is used.

**Describe the solution you'd like**
A dark themed loading screen. (I noticed that the loading screen indicates that it's loading the theme, so I don't know if there's an easy way to theme the loading screen, but maybe have a local storage key or etc with the background color, etc, for the loading screen, with a fallback to using a media query to see if the user prefers a dark or light theme? (that way they don't get a flash of white if the local storage key or etc isn't set))

**Describe alternatives you've considered**
Haven't tried it yet, but I could use darkreader to apply a dark theme to the URL, and then have it not run when it detects a dark theme (which means it should hopefully work for the loading screen, but stop re-themeing once dbgate loads in with its dark theme.

**Comment by LunarTwilight** [comment]
darkreader ended up not working too well (it didn't theme the loading screen fully and caused issues with my theme), so I wrote up this CSS instead for it that I'm injecting via stylus (tho I get a flash of white on the loading screen before stylus loads in said CSS)
```css
    .starting-dbgate {
        background: #282a36;
        color: #f8f8f2;
        .lds-ellipsis div {
            background: #f8f8f2 !important;
        }
    }
    ```
