### ISSUE TITLE
FEAT: OAuth support and default permissions

### ISSUE THREAD

**Issue by locomoco28** [dbgate/dbgate#407]
**Is your feature request related to a problem? Please describe.**

No problem, just a nice-to-have wish/idea for shared DBGate deployments as a web server.

**Describe the solution you'd like**

Instead of only offering user authentication using usernames and passwords, support OAuth providers like Github/Google/Microsoft etc. Permissions could still be set as environment variables using the user's ID

```env
# default: credentials
LOGIN_PROVIDERS=credentials,github

# current logins implementation

LOGIN_CREDENTIALS_USERS=user1
LOGIN_CREDENTIALS_USER_PASSWORD_user1=123
LOGIN_CREDENTIALS_PERMISSIONS_user1=~/connections/*, connections/con1

# Github OAuth

LOGIN_GITHUB_CLIENT_ID=[client_id]
LOGIN_GITHUB_CLIENT_SECRET=[client_secret]

# restrict uids that are allowed to login
# another option would be to disable all permissions by default for OAuth users perhaps?
LOGIN_GITHUB_USERS=[uid],[uid2]
LOGIN_GITHUB_USER_PERMISSIONS_[uid]=connections/con1

# optional default permissions
# could be written in JSON to make it easier to parse
LOGIN_GITHUB_DEFAULT_PERMISSIONS=~widgets/*,~/connections/*
```

This would be great to not necessarily have passwords stored in environment variables.

---

Another great option would be configuration files written in JSON or YAML that are placed in a specific folder using the provider's name like:

```json
// credentials.json
{
  "users": [
    {
      "name": "user1",
      "password": "123",
      "permissions": [
        "~/connections/*, connections/con1"
      ]
    }
  ],
}
```

```yaml
# github.yaml
config:
  clientId: [client_id]
  clientSecret: [client_secret]
users:
  - uid: [uid]
    permissions:
      - connections/con1
defaultPermissions:
  - ~widgets/*
  - ~connections/*
```

**Describe alternatives you've considered**
