### ISSUE TITLE
How to configure dbadmin?

### ISSUE THREAD

**Issue by bangouraboulaye** [dbgate/dbgate#442]
**Describe the bug**

dbgate working in docker container and on localhost:3000\dbadmin does not work.
We got this error: _Cannot GET /dbadmin_

 - Type - Web/Application
 - Database engine: [e.g. MySQL/PostgreSQL/SQL Server]

**Comment by janproch** [comment]
Did you try root URL http://localhost:3000 ?

For running under /dbadmin directory, explicit configuration must be used (using WEB_ROOT environment variable - https://dbgate.org/docs/env-variables.html )

**Comment by bangouraboulaye** [comment]
Yes  i tried, but it doesn't work!
Maybe i don't realy know how to configure it. The configuration should be with docker container in aws.
**how to configure it**? which file to use? docker-compose.yaml ?

thanks

**Comment by janproch** [comment]
You could use both ways docker-compose.yaml or running with ```docker run``` command.

Documentation on how to use dbgate with docker is here: https://hub.docker.com/r/dbgate/dbgate

I am not sure, how exactly it should be done in AWS, I have no experiences with AWS

**Comment by janproch** [comment]
I tried your configuration, and it worked. However, you pasted it here without whitespaces, which are significant in YAML, maybe this could be a problem. If you run docker-compose up, is there any error in console?


```
version: '3'
services:
  dbgate:
    image: dbgate/dbgate
    restart: always
    ports:
      - 80:3000
    volumes:
      - dbgate-data:/root/.dbgate
    environment:
      WEB_ROOT: /dbadmin
      LOGINS: admin
      LOGIN_PASSWORD: admin
      LOGIN_PERMISSIONS: ~*
volumes:
  dbgate-data:
    driver: local
```

**Comment by janproch** [comment]
There is one small mistake, if you want user admin with password admin, following config is necessary:

```
version: '3'
services:
  dbgate:
    image: dbgate/dbgate
    restart: always
    ports:
      - 80:3000
    volumes:
      - dbgate-data:/root/.dbgate
    environment:
      WEB_ROOT: /dbadmin
      LOGINS: admin
      LOGIN_PASSWORD_admin: admin
      LOGIN_PERMISSIONS: ~*
volumes:
  dbgate-data:
    driver: local
```
