### ISSUE TITLE
ENAMETOOLONG ssl mongodb

### ISSUE THREAD

**Issue by mhf-ir** [dbgate/dbgate#504]
Using docker latest alpine

Certificated tested with mongodump and also Mongoose nodejs. no problem with replication. but 

```
# POST | https://localhost:3000/server-connections/server-status

mongo	Object { name: "error", message: "ENAMETOOLONG: name too long, open '-----BEGIN CERTIFICATE-----\nMIIB3DCCAWOgAwIBAgIUV6.....
```

```yaml
  repl0-mongo0-web-ui:
    image: dbgate/dbgate:alpine
    container_name: repl0-mongo0-web-ui
    restart: always
    ports:
       - 3000:3000
    environment:
      - LOG_LEVEL=trace
      - CONNECTIONS=mongo
      - LABEL_mongo="MongoDB repl0-mongo0"
      - SERVER_mongo=repl0-mongo-0
      - URL_mongo=mongodb://repl0-mongo-0.localhost:27000,repl0-mongo-1.localhost:27010,repl0-mongo-2.localhost:27020/?replicaSet=repl0
      - USER_mongo=root
      - PASSWORD_mongo=REDACTED
      - ENGINE_mongo=mongo@dbgate-plugin-mongo
      - USE_SSL_mongo=1
      - SSL_CA_FILE_mongo=/cert/ca.pem
      - SSL_CERT_FILE_mongo=/cert/client-fullchain.pem
      - SSL_KEY_FILE_mongo=/cert/client-key.pem
    volumes:
      - ./cert:/cert:ro
```

Nothing special in logs files.

```
{"pid":128,"caller":"requirePlugin","name":"serverConnection","level":30,"msg":"Loading module dbgate-plugin-mongo from /home/dbgate-docker/plugins/dbgate-plugin-mongo/dist/backend.js","time":1677071822753}
{"pid":139,"caller":"connections","name":"serverConnection","connections":[{"_id":"***","engine":"mongo@dbgate-plugin-mongo","server":"***","user":"***","password":"***","databaseUrl":"***","useDatabaseUrl":true,"defaultDatabase":null,"singleDatabase":false,"displayName":"***","databases":null,"useSsl":"***","sslCaFile":"***","sslCertFile":"***","sslKeyFile":"***"}],"level":30,"msg":"Using connections from ENV variables","time":1677071862729}
{"pid":139,"caller":"requirePlugin","name":"serverConnection","level":30,"msg":"Loading module dbgate-plugin-mongo from /home/dbgate-docker/plugins/dbgate-plugin-mongo/dist/backend.js","time":1677071862756}
{"pid":150,"caller":"connections","name":"serverConnection","connections":[{"_id":"***","engine":"mongo@dbgate-plugin-mongo","server":"***","user":"***","password":"***","databaseUrl":"***","useDatabaseUrl":true,"defaultDatabase":null,"singleDatabase":false,"displayName":"***","databases":null,"useSsl":"***","sslCaFile":"***","sslCertFile":"***","sslKeyFile":"***"}],"level":30,"msg":"Using connections from ENV variables","time":1677071902732}
{"pid":150,"caller":"requirePlugin","name":"serverConnection","level":30,"msg":"Loading module dbgate-plugin-mongo from /home/dbgate-docker/plugins/dbgate-plugin-mongo/dist/backend.js","time":1677071902762}
{"pid":161,"caller":"connections","name":"serverConnection","connections":[{"_id":"***","engine":"mongo@dbgate-plugin-mongo","server":"***","user":"***","password":"***","databaseUrl":"***","useDatabaseUrl":true,"defaultDatabase":null,"singleDatabase":false,"displayName":"***","databases":null,"useSsl":"***","sslCaFile":"***","sslCertFile":"***","sslKeyFile":"***"}],"level":30,"msg":"Using connections from ENV variables","time":1677071942731}
{"pid":161,"caller":"requirePlugin","name":"serverConnection","level":30,"msg":"Loading module dbgate-plugin-mongo from /home/dbgate-docker/plugins/dbgate-plugin-mongo/dist/backend.js","time":1677071942761}

```
