### ISSUE TITLE
BUG: 5.2.6 version don's support sqlite3, 5.2.5 is ok

### ISSUE THREAD

**Issue by vasekch** [dbgate/dbgate#614]
**Describe the bug**

This is reopening issue #571 . It seems that docker image is missing GLIBC 2.29 library.

**To Reproduce**

From my docker-compose.yml
```
  ...
  db-admin:
    image: dbgate/dbgate
    environment:
      CONNECTIONS: core

      LABEL_core: core db
      FILE_core: /mnt/core_db/db.sqlite3
      ENGINE_core: sqlite@dbgate-plugin-sqlite
    volumes:
      - ./core/db:/mnt/core_db
    ports:
      - 9000:3000
    ...
```

Failed to use sqlite3 with latest docker 5.2.6.
If using 5.2.5 all works.

my docker log

```
db-admin_1      | {"pid":104,"caller":"requirePlugin","name":"databaseConnection","level":30,"msg":"Loading module dbgate-plugin-sqlite from /home/dbgate-docker/plugins/dbgate-plugin-sqlite/dist/backend.js","time":1692197335737}
db-admin_1      | {"pid":12,"caller":"databaseConnections","name":"main","level":50,"msg":"Error in database connection core, database db.sqlite3: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/dbgate-docker/node_modules/better-sqlite3/build/Release/better_sqlite3.node)","time":1692197335804}
db-admin_1      | {"pid":104,"caller":"dbconnProcess","name":"databaseConnection","err":{"code":"ERR_DLOPEN_FAILED"},"level":50,"msg":"Error in DB connection","time":1692197335803}
```

**Screenshots**

![image](https://github.com/dbgate/dbgate/assets/2572537/6f7e9260-7852-41ac-ba48-ccd5e29429fc)

**Version Information (please complete the following information):**

 - OS: Ubuntu 20.04
 - App Version 5.2.6
 - Install source Docker
 - Type - Docker image libraries
 - Database engine: SQLite3
