### ISSUE TITLE
BUG: docker version don's support sqlite3

### ISSUE THREAD

**Issue by echosun1996** [dbgate/dbgate#678]
**Details:**
After creating dbgate by docker-compose on my ARM macbook,  I see an error "/home/dbgate-docker/node_modules/better-sqlite3/build/Release/better_sqlite3.node: cannot open shared object file: No such file or directory" in the section "TABLES, VIEWS, FUNCTIONS".

Log in docker:
```
dbdocker-dbgate-1  | {"pid":176,"caller":"connections","name":"databaseConnection","connections":[{"_id":"***","engine":"sqlite@dbgate-plugin-sqlite","useDatabaseUrl":false,"databaseFile":"***","defaultDatabase":"***","singleDatabase":true,"displayName":"***","databases":null}],"level":30,"msg":"Using connections from ENV variables","time":1702617600704}
dbdocker-dbgate-1  | {"pid":176,"caller":"requirePlugin","name":"databaseConnection","level":30,"msg":"Loading module dbgate-plugin-sqlite from /home/dbgate-docker/plugins/dbgate-plugin-sqlite/dist/backend.js","time":1702617600722}
dbdocker-dbgate-1  | {"pid":1,"caller":"databaseConnections","name":"main","level":50,"msg":"Error in database connection sqlite, database depression.sqlite: /home/dbgate-docker/node_modules/better-sqlite3/build/Release/better_sqlite3.node: cannot open shared object file: No such file or directory","time":1702617600742}
dbdocker-dbgate-1  | {"pid":176,"caller":"dbconnProcess","name":"databaseConnection","err":{"code":"ERR_DLOPEN_FAILED"},"level":50,"msg":"Error in DB connection","time":1702617600742}
```

docker-compose:
```
version: '3'
services:
  dbgate:
    image: dbgate/dbgate
    restart: always
    ports:
      - 3080:3000
    volumes:
      - temp:/mnt/sqt
      - dbgate-data:/root/.dbgate
    environment:
      CONNECTIONS: sqlite

      LABEL_sqlite: sqt
      FILE_sqlite: /mnt/sqt/test.sqlite
      ENGINE_sqlite: sqlite@dbgate-plugin-sqlite

volumes:
  dbgate-data:
    driver: local
```

I also tried to install 5.2.5, 5.2.7, beta versions, but all failed. And open the application directly, and it works.

But I need to open it in docker and share the link with others.

**Version Information [might be relevant to your issue]**
Operating System: Mac OS 14.1.1 
App Version [help -> about]: 5.2.7

**Screenshot [if appropriate]**:
![sc](https://github.com/dbgate/dbgate/assets/19505192/fd3bcf60-a455-4742-8141-b23c65db4d82)
