### ISSUE TITLE
BUG: Say something here

### ISSUE THREAD

**Issue by meglio** [dbgate/dbgate#710]
**Describe the bug**

I cannot connect to sqlite file available in a mounted volume:

<img width="532" alt="image" src="https://github.com/dbgate/dbgate/assets/282177/83c78ff5-326f-481e-995c-d84c3692bf00">

The error message is not helpful.

**To Reproduce**

In docker-composer:

```
    dbgate:
        profiles: [ "dev" ]
        image: dbgate/dbgate:5.2.7
        restart: always
        ports:
            - "8587:3000"
        volumes:
            - sqlite:/app/sqlite
        environment:
            CONNECTIONS: perf
            LABEL_perf: Perf SQLite
            ENGINE_perf: sqlite@dbgate-plugin-sqlite
            FILE_perf: /app/sqlite/perf/perf.sqlite
```

Now when I open localhost:8586 in my browser and click on that preconfigured sqlite database, it shows the error as in the screenshot.

**Expected behavior**

Should just work.

**Version Information (please complete the following information):**

- Host machine: MacOS
- Environment: Docker Compose
 - Install source: Docker
 - Type - Web/Application
 - Database engine: SQLite
