### ISSUE TITLE
Multiple server connection (multiple databases), authorize against DB supported?

### ISSUE THREAD

**Issue by Kofl** [dbgate/dbgate#829]
Hi,

running dbgate as docker image, working great.

Is it supported to configure multiple server connections with authorize against DB?

So similar to:

```
    environment:
      CONNECTIONS: con1,con2

      LABEL_con1: MySql-xy
      SERVER_con1: 192.168.xy
       PORT_con1: 3306
      ENGINE_con1: mysql@dbgate-plugin-mysql
      PASSWORD_MODE_con1: askUser

      LABEL_con2: MySql-xz
      SERVER_con2: 192.168.xz
        PORT_con2: 3306
      ENGINE_con2: mysql@dbgate-plugin-mysql
      PASSWORD_MODE_con1: askUser
```

We only get the prompt for MySql-xy, also when we click on MySql-xz.

Thanks
